<script type="text/javascript" src="{{ asset('js/frontend/jquery-2.1.4.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/owl.carousel.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/chosen.jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/Modernizr.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/jquery-ui.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/lightbox.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/masonry.pkgd.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/imagesloaded.pkgd.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/isotope.pkgd.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/jquery.mCustomScrollbar.concat.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/jquery.parallax-1.1.3.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/jquery.magnific-popup.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/masonry.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/frontend/functions.js') }}"></script>
<script src="{{ asset("js/cart.js") }}" type="text/javascript"></script>
